# 基础配置
mixed-port: 7897
port: 7890
socks-port: 7891
ipv6: true
allow-lan: false
mode: Rule
log-level: info

# 前端控制器界面访问地址
external-controller: 127.0.0.1:9090
# 前端控制器界面 (archlinuxcn 源中的 metacubexd)
external-ui: /usr/share/metacubexd
# 前端控制器登录密码
# (因为监听的 127.0.0.1 只有本机能够访问, 暂不设置)
secret: ""

#【Meta专属】TCP连接并发，如果域名解析结果对应多个IP，
# 并发所有IP，选择握手最快的IP进行连接
tcp-concurrent: true

# 统一延迟 (用于更准确的测试代理延迟)
# 不太好用，故关闭
unified-delay: false

# 配置缓存 (选择的节点和 fake-ip 缓存)
profile:
  store-selected: true
  store-fake-ip: true


#【Meta专属】使用geoip.dat数据库( 默认：false 使用 mmdb 数据库)
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo/geoip-all.dat"
  geosite: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo/geosite-all.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo/Country-all.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo/Country-ASN-all.mmdb"


#【Meta专属】sniffer域名嗅探器
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
  force-domain:
    - 'google.com'


# DNS
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - geosite:fakeip-filter
  default-nameserver:
    - system
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  # nameserver-policy:
  #   "geosite:cn,private":
  #     - https://doh.pub/dns-query
  #     - https://dns.alidns.com/dns-query
  #   "geosite:ads":
  #     - rcode://success
  #   "geosite:proxy":
  #     - https://dns.google/dns-query
  #     - https://cloudflare-dns.com/dns-query


